name: MyShuttle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
        java-package: jdk
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Junit Tests
      run: mvn -B test --file pom.xml
    
#     - run: mkdir staging && cp target/*.war staging
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      id: test-results
      if: always ()
      with:
        files: target/surefire-reports/*.xml
    
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: ${{github.workspace}}/target
