name: MyShuttle

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        java-package: jdk
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Junit Tests
      run: mvn -B test --file pom.xml
    
    - run: mkdir staging && cp target/*.war staging

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      id: test-results
      if: always ()
      with:
        files: target/surefire-reports/*.xml
    
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
